// config.bin - 11:14:00 04/30/15, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class A3_Weapons_F_Launchers_LAW {
		units[] = {};
		weapons[] = {"launch_RPG32_F"};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Weapons_F"};
	};
};
class Mode_SemiAuto;	// External class reference

class CfgWeapons {
	class Launcher;	// External class reference
	
	class Launcher_Base_F : Launcher {
		class WeaponSlotsInfo;	// External class reference
	};
	
	class launch_RPG32_F : Launcher_Base_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "launch_RPG32_F";
		scope = 2;
		displayName = "$STR_A3_CfgWeapons_launch_LAW0";
		model = "\A3\weapons_f\launchers\RPG32\rpg32_F.p3d";
		picture = "\A3\Weapons_F\launchers\RPG32\data\UI\gear_RPG32_X_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\A3\Weapons_F\Launchers\RPG32\data\Anim\RPG32.rtm"};
		reloadAction = "ReloadRPG";
		recoil = "recoil_rpg";
		modelOptics = "\A3\Weapons_F\acc\reticle_RPG_F";
		weaponInfoType = "RscWeaponEmpty";
		opticsZoomMin = 0.1083;
		opticsZoomMax = 0.1083;
		opticsZoomInit = 0.1083;
		cameraDir = "look";
		
		class GunParticles {
			class effect1 {
				positionName = "konec hlavne";
				directionName = "usti hlavne";
				effectName = "RocketBackEffectsRPGNT";
			};
		};
		
		class OpticsModes {
			class optic {
				opticsID = 1;
				useModelOptics = 1;
				opticsZoomMin = 0.1083;
				opticsZoomMax = 0.1083;
				opticsZoomInit = 0.1083;
				distanceZoomMin = 300;
				distanceZoomMax = 300;
				memoryPointCamera = "eye";
				opticsFlare = 1;
				opticsDisablePeripherialVision = 1;
				cameraDir = "look";
				visionMode[] = {"Normal", NVG};
				opticsPPEffects[] = {"OpticsCHAbera1", "OpticsBlur1"};
			};
		};
		magazines[] = {RPG32_F, RPG32_HE_F};
		modes[] = {"Single"};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound"};
			
			class BaseSoundModeType {};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"A3\Sounds_F\arsenal\weapons\Launchers\RPG32\rpg32", 1.99526, 1, 1500};
				soundBegin[] = {"begin1", 1};
			};
			recoil = "recoil_single_law";
			aiRateOfFire = 7.0;
			aiRateOfFireDistance = 600;
			minRange = 10;
			minRangeProbab = 0.3;
			midRange = 400;
			midRangeProbab = 0.8;
			maxRange = 600;
			maxRangeProbab = 0.1;
		};
		drySound[] = {"A3\Sounds_F\arsenal\weapons\Launchers\RPG32\Dry_RPG32", 0.446684, 1, 20};
		reloadMagazineSound[] = {"A3\Sounds_F\arsenal\weapons\Launchers\RPG32\reload_RPG32", 1.0, 1, 10};
		soundFly[] = {"A3\Sounds_F\arsenal\weapons\Launchers\RPG32\Fly_RPG32", 0.316228, 1.5, 900};
		canLock = 0;
		weaponLockDelay = 3.0;
		lockAcquire = 0;
		inertia = 0.9;
		dexterity = 1.1;
		
		class WeaponSlotsInfo : WeaponSlotsInfo {
			mass = 100;
		};
		descriptionShort = "$STR_A3_CfgWeapons_launch_LAW1";
		
		class Library {
			libTextDesc = "$STR_A3_CfgWeapons_launch_LAW_Library0";
		};
	};
};
