class CfgMagazines
{
	class CA_Magazine;
	#include "Items\cfgItems.cpp"
	#include "Ammunition\45ACP.cpp"
	#include "Ammunition\762x51.cpp"
	
	// MEAT
	#include "Food\Meat\rawmutton.cpp"
	#include "Food\Meat\rawchicken.cpp"
	#include "Food\Meat\rawgoat.cpp"
	#include "Food\Meat\cookedmutton.cpp"
	#include "Food\Meat\cookedchicken.cpp"
	#include "Food\Meat\cookedgoat.cpp"
	
	// FOOD
	#include "Food\cannedfood.hpp"
	#include "Food\tacticalbacon.hpp"
	#include "Food\carrot.hpp"
	#include "Food\cereal.hpp"
	#include "Food\powderedmilk.hpp"
	#include "Food\coffee.hpp"
	#include "Food\mre.hpp"
	#include "Food\corn.hpp"
	#include "Food\donut.hpp"
	#include "Food\potato.hpp"
	#include "Food\rice.hpp"
	#include "Food\twinkies.hpp"
	#include "Food\snack_cakes.hpp"
	#include "Food\snoballs.hpp"
	#include "Food\juicebox.hpp"
	#include "Food\soda.hpp"
	#include "Food\energy_drink.hpp"
	#include "Food\dirty_water.hpp"
	#include "Food\waterbottle.hpp"
	#include "Food\empty_bottle.hpp"
	
	// MEDICAL
	#include "Medical\bandage.hpp"
	#include "Medical\blood.hpp"
	#include "Medical\brace.hpp"
	#include "Medical\disinfectant.hpp"
	#include "Medical\elasticbandage.hpp"
	#include "Medical\epinephrine.hpp"
	#include "Medical\ibuprofen.hpp"
	#include "Medical\morphine.hpp"
	#include "Medical\penicillin.hpp"
	#include "Medical\syringe.hpp"
	#include "Medical\tourniquet.hpp"
	
	// TOOLS
	#include "Tools\axe.hpp"
	#include "Tools\barbedwire.hpp"
	#include "Tools\fireaxe.hpp"
	#include "Tools\hammer.hpp"
	#include "Tools\jerrycan.hpp"
	#include "Tools\jumpercables.hpp"
	#include "Tools\nails.hpp"
	#include "Tools\paintcan.hpp"
	#include "Tools\sandbag.hpp"
	#include "Tools\scrap.hpp"
	#include "Tools\shovel.hpp"
	#include "Tools\tape.hpp"
	#include "Tools\tire.hpp"
	#include "Tools\toolbox.hpp"
	#include "Tools\wrench.hpp"
	
	// SURVIVAL
	#include "Survival\knife.hpp"
	#include "Survival\matches.hpp"
	#include "Survival\switchblade.hpp"
	#include "Survival\tent.hpp"
	#include "Survival\rope.hpp"
	#include "Survival\battery.hpp"
	#include "Survival\bedroll.hpp"
	#include "Survival\rock.hpp"
	#include "Survival\lighter.hpp"
};