// config.bin - 00:26:29 05/17/15, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class Trixie_Rifles {
		requiredaddons[] = {"A3_Weapons_F", "asdg_jointrails"};
		requiredversion = 1.0;
		units[] = {"Trixie_Rifle_equipbox"};
		weapons[] = {"Trixie_Enfield", "Trixie_Enfield_Rail", "Trixie_CZ550", "Trixie_CZ550_Rail", "Trixie_FNFAL_Rail"};
		Magazines[] = {"Trixie_Enfield_Mag", "Trixie_CZ550_Mag", "Trixie_FNFAL_Mag", "Trixie_FNFAL_Mag_T"};
		ammo[] = {"Trixie_FNFAL_Ball", "Trixie_303_Ball"};
	};
};

class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference
class Mode_FullAuto;	// External class reference
class asdg_OpticRail1913;	// External class reference
class asdg_FrontSideRail;	// External class reference

class CfgWeapons {
	class srifle_EBR_F;	// External class reference
	
	class Trixie_Enfield : srifle_EBR_F {
		scope = 2;
		author = "Trixie";
		displayname = "Lee Enfield Mk III";
		descriptionshort = "WW2 Rifle <br/>Caliber: 7.7mm";
		
		class Library {
			libtextdesc = "The iconic Lee-Enfield rifle, the Mk III, was introduced on 26 January 1907 and featured a simplified rear sight arrangement and a fixed, rather than a bolt-head-mounted sliding, charger guide.The Mk III saw extensive service throughout the World War and Second World War as well. <br/>The SMLE Mk III uses the ,303 caliber ammo.";
		};
		magazines[] = {"Trixie_Enfield_Mag"};
		picture = "\Trixie_Rifles\UI\enfield.paa";
		model = "Trixie_Rifles\trixie_enfield.p3d";
		handAnim[] = {"OFP2_ManSkeleton", "\trixie_rifles\anim\LeeEnfield.rtm"};
		modes[] = {"Single", "single_close_optics1", "single_medium_optics1", "single_far_optics1"};
		discretedistance[] = {100, 200, 300, 400, 500};
		discretedistanceinitindex = 0;
		reloadaction = "GestureReloadEBR";
		reloadmagazinesound[] = {"A3\sounds_f\weapons\reloads\new_ebr", 0.630957, 1, 35};
		
		class WeaponSlotsInfo {
			allowedslots[] = {901};
			mass = 60;
			
			class MuzzleSlot {
				access = 1;
				compatibleitems[] = {};
				displayname = "Muzzle Slot";
				linkproxy = "\A3\data_f\proxies\weapon_slots\MUZZLE";
				scope = 0;
			};
			
			class asdg_FrontSideRail_rifles : asdg_FrontSideRail {};
			
			class asdg_OpticRail_rifles : asdg_OpticRail1913 {};
		};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				closure1[] = {"A3\sounds_f\Closure\closure_rifle_2.wss", 3.16228, 1, 500};
				closure2[] = {"A3\sounds_f\Closure\closure_rifle_3.wss", 3.16228, 1, 500};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
				weaponSoundEffect = "DefaultRifle";
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"trixie_rifles\sound\Enfield_1.wss", 1.58489, 1, 1200};
				soundbegin[] = {"begin1", 1};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"A3\sounds_f\weapons\silenced\silent-01", "db-1", 1, 200};
				begin2[] = {"A3\sounds_f\weapons\silenced\silent-02", "db-1", 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			reloadTime = 1.5;
			dispersion = 0.0005;
			minRange = 2;
			minRangeProbab = 0.3;
			midRange = 250;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.05;
			recoil = "recoil_single_ebr";
			recoilprone = "recoil_single_prone_ebr";
		};
		
		class single_close_optics1 : Single {
			requiredOpticType = 1;
			showToPlayer = 0;
			minRange = 2;
			minRangeProbab = 0.05;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 500;
			maxRangeProbab = 0.01;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
		};
		
		class single_medium_optics1 : single_close_optics1 {
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 500;
			midRangeProbab = 0.7;
			maxRange = 700;
			maxRangeProbab = 0.05;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
		};
		
		class single_far_optics1 : single_medium_optics1 {
			requiredOpticType = 2;
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 600;
			midRangeProbab = 0.4;
			maxRange = 900;
			maxRangeProbab = 0.05;
			aiRateOfFire = 4;
			aiRateOfFireDistance = 600;
		};
		aiDispersionCoefY = 3;
		aiDispersionCoefX = 2;
	};
	
	class Trixie_Enfield_Rail : Trixie_Enfield {
		scope = 2;
		author = "Trixie";
		displayname = "Lee Enfield Mk III (Rail)";
		model = "Trixie_Rifles\trixie_enfield_rail.p3d";
		
		class WeaponSlotsInfo {
			allowedslots[] = {901};
			mass = 60;
			
			class MuzzleSlot {
				access = 1;
				compatibleitems[] = {};
				displayname = "Muzzle Slot";
				linkproxy = "\A3\data_f\proxies\weapon_slots\MUZZLE";
				scope = 0;
			};
			
			class asdg_FrontSideRail_rifles : asdg_FrontSideRail {};
			
			class asdg_OpticRail_rifles : asdg_OpticRail1913 {};
		};
	};
	
	class Trixie_CZ550_Rail : srifle_EBR_F {
		scope = 2;
		author = "Trixie";
		displayname = "CZ 550 w/Rail";
		descriptionshort = "CZ 550 Hunting Rifle <br/>Caliber: 9.3x62mm";
		
		class Library {
			libtextdesc = "CZ 550 is an improved Mauser 98-type hunting rifle. It features solid head lugs, fixed ejector, claw extractor, single-set trigger, square bridge dovetailed receiver and classic-styled walnut stock.<br/>This weapon uses 9.3x62 mm cartridges and features an additional optical scope.";
		};
		magazines[] = {"Trixie_CZ550_Mag"};
		picture = "\Trixie_Rifles\UI\cz.paa";
		model = "Trixie_Rifles\trixie_huntingrifle_rail.p3d";
		handAnim[] = {"OFP2_ManSkeleton", "\trixie_rifles\anim\LeeEnfield.rtm"};
		modes[] = {"Single", "single_close_optics1", "single_medium_optics1", "single_far_optics1"};
		discretedistance[] = {100, 200, 300};
		discretedistanceinitindex = 0;
		reloadaction = "GestureReloadEBR";
		reloadmagazinesound[] = {"A3\sounds_f\weapons\reloads\new_ebr", 0.630957, 1, 35};
		
		class WeaponSlotsInfo {
			allowedslots[] = {901};
			mass = 60;
			
			class MuzzleSlot {
				access = 1;
				compatibleitems[] = {};
				displayname = "Muzzle Slot";
				linkproxy = "\A3\data_f\proxies\weapon_slots\MUZZLE";
				scope = 0;
			};
			
			class asdg_FrontSideRail_rifles : asdg_FrontSideRail {};
			
			class asdg_OpticRail_rifles : asdg_OpticRail1913 {};
		};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				closure1[] = {"A3\sounds_f\Closure\closure_rifle_2.wss", 3.16228, 1, 500};
				closure2[] = {"A3\sounds_f\Closure\closure_rifle_3.wss", 3.16228, 1, 500};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
				weaponSoundEffect = "DefaultRifle";
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"trixie_rifles\sound\rifle_1.wss", 1.58489, 1, 1200};
				soundbegin[] = {"begin1", 1};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"A3\sounds_f\weapons\silenced\silent-01", "db-1", 1, 200};
				begin2[] = {"A3\sounds_f\weapons\silenced\silent-02", "db-1", 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			reloadTime = 2;
			dispersion = 0.0005;
			minRange = 2;
			minRangeProbab = 0.3;
			midRange = 250;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.05;
			recoil = "recoil_single_ebr";
			recoilprone = "recoil_single_prone_ebr";
		};
		
		class single_close_optics1 : Single {
			requiredOpticType = 1;
			showToPlayer = 0;
			minRange = 2;
			minRangeProbab = 0.05;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 500;
			maxRangeProbab = 0.01;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
		};
		
		class single_medium_optics1 : single_close_optics1 {
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 500;
			midRangeProbab = 0.7;
			maxRange = 700;
			maxRangeProbab = 0.05;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
		};
		
		class single_far_optics1 : single_medium_optics1 {
			requiredOpticType = 2;
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 600;
			midRangeProbab = 0.4;
			maxRange = 900;
			maxRangeProbab = 0.05;
			aiRateOfFire = 4;
			aiRateOfFireDistance = 600;
		};
		aiDispersionCoefY = 3;
		aiDispersionCoefX = 2;
	};
	
	class Trixie_CZ550 : Trixie_CZ550_Rail {
		displayname = "CZ 550";
		author = "Trixie";
		model = "Trixie_Rifles\trixie_huntingrifle.p3d";
		modeloptics = "Trixie_Rifles\2Dscope_Hunter_12";
		opticsppeffects[] = {"OpticsCHAbera2", "OpticsBlur2"};
		opticszoominit = 0.083;
		opticszoommax = 0.083;
		opticszoommin = 0.0208;
		discretedistance[] = {100, 200, 300, 400, 500, 600, 700, 800};
		discretedistanceinitindex = 2;
	};
	
	class Trixie_FNFAL_Rail : srifle_EBR_F {
		scope = 2;
		author = "Trixie";
		displayname = "FN FAL w/ Rail";
		descriptionshort = "Battle Rifle<br/>Caliber: 7.62x51mm NATO";
		
		class Library {
			libtextdesc = "The Fusil Automatique Léger (Light Automatic Rifle) or FAL is a self-loading, selective fire rifle produced in the Belgium. During the Cold War it was adopted by many NATO countries, with the notable exception of the United States.<br/>Because of its prevalence and widespread use among the armed forces of many Western and other non-Communist countries during the Cold War it was nicknamed 'the right arm of the Free World'.";
		};
		magazines[] = {"Trixie_FNFAL_Mag", "Trixie_FNFAL_Mag_T", "20Rnd_762x51_Mag"};
		picture = "\Trixie_Rifles\UI\fnfal.paa";
		model = "Trixie_Rifles\fnfal_rail.p3d";
		handAnim[] = {"OFP2_ManSkeleton", "\trixie_rifles\anim\SCAR.rtm"};
		modes[] = {"Single", "Burst", "single_close_optics1", "single_medium_optics1", "single_far_optics1"};
		discretedistance[] = {100, 200, 300, 400, 500, 600};
		discretedistanceinitindex = 0;
		reloadaction = "GestureReloadEBR";
		reloadmagazinesound[] = {"A3\sounds_f\weapons\reloads\new_ebr", 0.630957, 1, 35};
		
		class WeaponSlotsInfo {
			allowedslots[] = {901};
			mass = 60;
			
			class MuzzleSlot {
				access = 1;
				compatibleitems[] = {"muzzle_snds_B"};
				displayname = "Muzzle Slot";
				linkproxy = "\A3\data_f\proxies\weapon_slots\MUZZLE";
				scope = 0;
			};
			
			class asdg_FrontSideRail_xm8 : asdg_FrontSideRail {};
			
			class asdg_OpticRail_xm8 : asdg_OpticRail1913 {};
		};
		
		class Single : Mode_SemiAuto {
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				closure1[] = {"A3\sounds_f\Closure\closure_rifle_2.wss", 3.16228, 1, 500};
				closure2[] = {"A3\sounds_f\Closure\closure_rifle_3.wss", 3.16228, 1, 500};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
				weaponSoundEffect = "DefaultRifle";
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"trixie_rifles\sound\FNFAL_single_1.wss", 2, 1, 2000};
				begin2[] = {"trixie_rifles\sound\FNFAL_single_1.wss", 2, 1, 2000};
				soundbegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"A3\sounds_f\weapons\silenced\silent-01", "db-1", 1, 200};
				begin2[] = {"A3\sounds_f\weapons\silenced\silent-02", "db-1", 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			dispersion = 0.0005;
			maxrange = 600;
			maxrangeprobab = 0.05;
			midrange = 250;
			midrangeprobab = 0.7;
			minrange = 2;
			minrangeprobab = 0.3;
			recoil = "recoil_single_ebr";
			recoilprone = "recoil_single_prone_ebr";
			reloadtime = 0.0857632;
		};
		
		class Burst : Mode_Burst {
			sounds[] = {"StandardSound", "SilencedSound"};
			
			class BaseSoundModeType {
				closure1[] = {"A3\sounds_f\Closure\closure_rifle_2.wss", 3.16228, 1, 500};
				closure2[] = {"A3\sounds_f\Closure\closure_rifle_3.wss", 3.16228, 1, 500};
				soundClosure[] = {"closure1", 0.5, "closure2", 0.5};
				weaponSoundEffect = "DefaultRifle";
			};
			
			class StandardSound : BaseSoundModeType {
				begin1[] = {"trixie_rifles\sound\FNFAL_single_1.wss", 2, 1, 2000};
				begin2[] = {"trixie_rifles\sound\FNFAL_single_1.wss", 2, 1, 2000};
				soundbegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			
			class SilencedSound : BaseSoundModeType {
				begin1[] = {"A3\sounds_f\weapons\silenced\silent-01", "db-1", 1, 200};
				begin2[] = {"A3\sounds_f\weapons\silenced\silent-02", "db-1", 1, 200};
				soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			};
			dispersion = 0.0005;
			maxrange = 600;
			maxrangeprobab = 0.05;
			midrange = 250;
			midrangeprobab = 0.7;
			minrange = 2;
			minrangeprobab = 0.3;
			recoil = "recoil_single_ebr";
			recoilprone = "recoil_single_prone_ebr";
			reloadtime = 0.0857632;
		};
		
		class single_close_optics1 : Single {
			requiredOpticType = 1;
			showToPlayer = 0;
			minRange = 2;
			minRangeProbab = 0.05;
			midRange = 300;
			midRangeProbab = 0.8;
			maxRange = 500;
			maxRangeProbab = 0.01;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 300;
		};
		
		class single_medium_optics1 : single_close_optics1 {
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 500;
			midRangeProbab = 0.7;
			maxRange = 700;
			maxRangeProbab = 0.05;
			aiRateOfFire = 2;
			aiRateOfFireDistance = 500;
		};
		
		class single_far_optics1 : single_medium_optics1 {
			requiredOpticType = 2;
			minRange = 300;
			minRangeProbab = 0.05;
			midRange = 600;
			midRangeProbab = 0.4;
			maxRange = 900;
			maxRangeProbab = 0.05;
			aiRateOfFire = 4;
			aiRateOfFireDistance = 600;
		};
		aiDispersionCoefY = 3;
		aiDispersionCoefX = 2;
	};
};

class CfgAmmo {
	class B_762x51_Ball;	// External class reference
	class B_408_Ball;	// External class reference
	
	class Trixie_FNFAL_Ball : B_762x51_Ball {
		maxSpeed = 840;
		model = "\A3\Weapons_f\Data\bullettracer\tracer_red";
	};
	
	class Trixie_303_Ball : B_408_Ball {
		hit = 14;
		maxSpeed = 744;
		model = "\A3\Weapons_f\Data\bullettracer\tracer_red";
	};
};

class CfgMagazines {
	class 7Rnd_408_Mag;	// External class reference
	class 20Rnd_762x51_Mag;	// External class reference
	
	class Trixie_Enfield_Mag : 7Rnd_408_Mag {
		scope = 2;
		author = "Trixie";
		count = 10;
		descriptionshort = "Caliber: .303<br />Rounds: 10<br />Used in: Lee Enfield Mk III";
		displayname = "10Rnd 7.7mm";
		ammo = "Trixie_303_Ball";
		picture = "\Trixie_rifles\UI\enfield_mag.paa";
		lastroundstracer = 0;
		tracersevery = 0;
	};
	
	class Trixie_CZ550_Mag : 7Rnd_408_Mag {
		scope = 2;
		author = "Trixie";
		count = 5;
		descriptionshort = "Caliber: 9.3x62mm<br />Rounds: 5<br />Used in: CZ 550";
		displayname = "5Rnd 9.3x62mm";
		ammo = "Trixie_303_Ball";
		picture = "\Trixie_rifles\UI\enfield_mag.paa";
		lastroundstracer = 0;
		tracersevery = 0;
	};
	
	class Trixie_FNFAL_Mag : 20Rnd_762x51_Mag {
		scope = 2;
		author = "Trixie";
		count = 20;
		descriptionshort = "Caliber: 7.62x51mm<br />Rounds: 20<br />Used in: FN FAL";
		displayname = "20Rnd 7.62x51mm FN FAL";
		ammo = "Trixie_FNFAL_Ball";
		picture = "\Trixie_rifles\UI\fnfal_mag.paa";
		lastroundstracer = 4;
		tracersevery = 4;
	};
	
	class Trixie_FNFAL_Mag_T : 20Rnd_762x51_Mag {
		scope = 2;
		author = "Trixie";
		count = 20;
		descriptionshort = "Caliber: 7.62x51mm<br />Rounds: 20<br />Used in: FN FAL";
		displayname = "20Rnd 7.62x51mm FN FAL (Tracer)";
		ammo = "Trixie_FNFAL_Ball";
		picture = "\Trixie_rifles\UI\fnfal_mag.paa";
		lastroundstracer = 1;
		tracersevery = 1;
	};
};
