/*
	Contains a list of game variables
	@author: TheAmazingAussie
*/

FULL_HEALTH = 6000;

LOOT_SPAWN_RADIUS = 150;
MAX_INFECTED_CITY = 10;

MIN_LOOT_SPAWN_DISTANCE = 30;
MIN_ZOMBIE_SPAWN_DISTANCE = 30;

DEAD_ZOMBIE_DESPAWN_TIME = 1800; // 30 minutes
DEAD_PLAYER_DESPAWN_TIME = 1800; // 30 minutes